### ISSUE TITLE
Push rights

### ISSUE THREAD

**Issue by demidan** [ckorikov/simket#1]
Constantine, please add me rights to push the code,
just adding to the project is not enough.
Thanks,
    Daniil

**Comment by ckorikov** [comment]
The master branch is protected. @demidan, use your own branch.

**Comment by demidan** [comment]
I know, I already found, that it may be protected.
I tried to do «git checkout -b <my branch name>; git push -u origin <my
branch name>»,
but it didn't work either.

OK, I'll try from the scratch today evening.

Regards,
    Daniil

**Comment by ckorikov** [comment]
Any updates?

**Comment by demidan** [comment]
Hi, sorry for not updating for a long time.
I've tried again from the scratch, made sure I do not have any changes in master -- everything in a new branch,
but I anyway getting error message when try to push:
> git.exe push --progress "origin" demidan_experimens
> 
> remote: Permission to ckorikov/simket.git denied to demidan.
> fatal: unable to access 'https://github.com/ckorikov/simket/': The requested URL returned error: 403
> 
> git did not exit cleanly (exit code 128) 

Also in web interface when clicking on "Upload files" I see "Uploads are disabled. File uploads require push access to this repository."
Do you have any other ideas to try?

For now, please see the code in my fork.

PS: I'd be unavailable for the following week including the weekend, alas :(

**Comment by ckorikov** [comment]
It seems I see the issue. Perhaps you didn't approve the invitation. See the attached screenshot.
<img width="740" alt="screenshot 2018-11-12 at 21 40 33" src="https://user-images.githubusercontent.com/10579090/48368063-b7b67780-e6c3-11e8-8109-7e418675449a.png">
